# Project information
site_name: My MkDocs Material Documentation
site_description: My personal Portfolio site using MkDocs Material
site_url: https://magus1968.github.io/Portfolio/

# Repository
repo_name: magus1968/Portfolio
repo_url: https://github.com/magus1968/Portfolio

# Configuration
theme:
  name: material
  language: ru
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        # icon: material/brightness-4 # Закомментировал класс допы от James Willett
        name: Dark mode
      # primary: green
      # accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        # icon: material/brightness-7
        name: Light mode
      # primary: blue
      # accent: deep orange
  features:               # Не делал search и tags. Если захочу — см. Thomas Wilde
    - navigation.instant
    - navigation.instant.progress
#    - navigation.instant.preview   # Почему-то не хочет принимать эту запись
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate   # Вообще мне понравилось такая структура - ВЕРНУТЬ [!]
    - navigation.top
    - content.code.copy
    - content.code.annotate
  icon:
    annotation: material/plus-circle
#
#  font:   # Пока шрифт менять не буду - неясно как работает с кириллицей
#    text: Merriweather Sans
#    code: Red Hat Mono
#
#  logo: assets/logo.png         # Чтобы добавить свой индивидуальный логотип и фавикон:
#  favicon: assets/favicon.ico   # нужно их сначала создать :)
#
#  icon:
#    logo: fontawesome/solid/home-alt
#
#  features:   # Пока не зашла навигация, отменил
#    - navigation.footer

# Plugins (! Внимание - у разработчика нет плагина glightbox !)
plugins:
  - search
  - blog
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - footnotes   # Это отсебятина - добавил не думая в поисках решения траблы с LinkedIn

# Page tree (см. репозиторий разработчика - лучше поймешь структуру)
nav:
  - Home: index.md
  - Getting started:
    - Python: coding/my-first-python-file.md
    - Adominition: admonitions.md
    - Content Tabs: content-tabs.md
    - Diagram: diagram-example.md
    - Codeblock Example: code-examples.md
  - About:   # Обо мне - можно по русски писать
    - About Me: about/about.md
    - Childhood: about/childhood.md
    - Current Projects: about/projects.md
  - Blog:
    - blog/index.md

# Additional configuration
extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@wizard_me
      name: YouTube
    - icon: simple/github
      link: https://github.com/magus1968
      name: GitHub
    - icon: simple/telegram
      link: https://t.me/mr_magus
      name: Telegram

# Copyright
copyright: Copyright &copy; 2025 Алексей Смирнов