site_name: My MkDocs Material Documentation
site_description: My personal Portfolio site using MkDocs Material
site_url: https://sitename.example
theme:
  name: material
  language: ru
  palette:

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        # icon: material/brightness-4 # Закомментировал класс допы от James Willett
        name: Dark mode
      # primary: green
      # accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        # icon: material/brightness-7
        name: Light mode
      # primary: blue
      # accent: deep orange
  features:               # Не делал search и tags. Если захочу — см. Thomas Wilde
    - navigation.instant
    - navigation.instant.progress
#    - navigation.instant.preview   # Почему-то не хочет принимать эту запись
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate   # Вообще мне понравилось такая структура - ВЕРНУТЬ [!]
    - navigation.top
    - content.code.copy

#
#  font:   # Пока шрифт менять не буду - неясно как работает с кириллицей
#    text: Merriweather Sans
#    code: Red Hat Mono
#
#  logo: assets/logo.png         # Чтобы добавить свой индивидуальный логотип и фавикон:
#  favicon: assets/favicon.ico   # нужно их сначала создать :)
#
#  icon:
#    logo: fontawesome/solid/home-alt
#
#  features:   # Пока не зашла навигация, отменил
#    - navigation.footer

plugins:
  - blog

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes   # Это отсебятина - добавил не думая в поисках решения траблы с LinkedIn

nav:
  - Home: index.md
  - Code Docs:
    - Python: coding/my-first-python-file.md
  - About:   # Обо мне - можно по русски писать
    - Current Projects: about/projects.md
    - About Me: about/about.md
    - Childhood: about/childhood.md
  - Blog:
    - blog/index.md

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@wizard_me
    - icon: simple/github
      link: https://github.com/magus1968

copyright: Copyright &copy; 2025 Алексей Смирнов